### ISSUE TITLE
Реализовать классификацию бактерий

### ISSUE THREAD

**Issue by LuninaPolina** [LuninaPolina/SecondaryStructureAnalyzer#2]
Нужно расширить существующий классификатор тРНК на археи, бактерии, растения и грибы на уровень вглубь по дереву жизни -- научиться различать между собой некоторые основные типы бактерий. Вот [тут](https://micropspbgmu.ru/micropspbgmu/Morph_files/sistematika-taksonomiya-i-klassifikatsiya-bakteriy.pdf) в таблице 4 перечислены 8 типов бактерий, имеющих медицинское значение. 

Предлагается взять на выбор одну из нейронных сетей  [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended) и [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended) и используя ее веса, попробовать добавить разделение внутри царства бактерии на 9 групп (Actinobacteria, Bacteroidetes, Chlamidiae, Firmicutes, Fusobacteria, Proteobacteria, Spirochaetes, Tenericutes, other). Предполагается, что, несмотря на то, что поменялись входные и выходные данные, обученные модели уже умеют извлекать основные фичи, поэтому дообучения будет достаточно.

Что нужно.

1. Подготовить данные. В [этом файле](https://mega.nz/file/lK40nBgZ#CXaYK3wwxI6aQlRAdW77BqbX8Ml6_YhBQtOYtPH8HbQ) перечислено, к какому из вышеописанных типов принадлежит каждая бактериальная цепочка из выборок train, valid, test моделей [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended) и [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended).  Следует учесть, что типы представлены не в равном количестве и выборку надо как-то сбалансировать.
2. Сконструировать нейронную сеть, используя верхние слои  [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended) или [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended) с подгруженными весами.
3. Обучить и протестировать модель для 6 классов по метрикам accuracy, precision и recall.

**Comment by vokor** [comment]
Буду делать эту задачу
