### ISSUE TITLE
Дополнить классификатор тРНК по царствам живых организмов

### ISSUE THREAD

**Issue by LuninaPolina** [LuninaPolina/SecondaryStructureAnalyzer#4]
По одной из популярных классификаций известно 6 царств живых организмов: животные, растения, грибы, протисты, археи и бактерии. Уже сделан классификатор на археи, бактерии, растения, грибы. Предлагается исследовать, можно ли расширить его (а конкретно, одну из нейронных сетей [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended) или [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended) на выбор) так, чтобы он мог различать не 4 царства, а все 6. Предполагается, что так как большая часть групп и общие закономерности нейронной сети уже известны, заново обучать модели с использованием парсинга не понадобится, и будет достаточно дообучения с использованием старых весов.

Основные шаги эксперимента.

1. Подготовить данные: цепочки тРНК для двух недостающих классов.
2. Сконструировать нейронную сеть: за основу взять слои  [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended) или [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended), используя веса уже обученной модели. Модифицировать данную модель, заменив часть слоев в конце так, чтобы она работала для 6 классов.
3. Обучить и протестировать модель для 6 классов по метрикам accuracy, precision и recall.

**Comment by DmiitriyJarosh** [comment]
Буду делать эту задачу
