### ISSUE TITLE
Определить наиболее значимые для классификации особенности цепочки тРНК

### ISSUE THREAD

**Issue by LuninaPolina** [LuninaPolina/SecondaryStructureAnalyzer#5]
Нужно для моделей [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended) и [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended) выяснить, какие особенности входных последовательностей оказались наиболее важными для классификации. 
Данные модели состоят из двух участков: 

- Преобразование цепочки в несколько трансформированный результат парсинга: изображение, к которому применили свертку и линеаризацию, в случае 1 и веторизованную матрицу разбора в случае 2 (N3).
- Обработка результата парсинга и собственно проведение классификации (N1 и N2).

![nn_all](https://user-images.githubusercontent.com/17449563/99293405-a9bc0400-2853-11eb-9725-1da64293bdac.png)

Ожидается, что, проанализировав веса на стыке этих участков можно достать информацию о том, что оказалось важно при обучении классификаторов.

Требуется сделать следующее.

1. В процессе работы с кокнретной цепочкой аккуратно достать значения со слоев стыка для обеих моделей.
2. Обработать и представить это в виде двумерной структуры (картинки). Для модели [1](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/imagesExtended)  нужно будет обратить результат работы слоя flatten, а для модели [2](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/tree/master/TrnaClassification/abfp/vectorsExtended) -- преобразовать вектор в матрицу (тут в приницпе можно заюзать функцию vec2img из [вот этого ](https://github.com/LuninaPolina/SecondaryStructureAnalyzer/blob/master/TrnaClassification/scripts/vectors2images.py) скрипта, он как раз обращает векторизацию матриц разбора).
3. Соотнести эту структуру с собственно цепочкой РНК: написать скрипт, принимающий цепочку и визуализирующий на ней участки, оказавшиеся важными для решения задачи классификации.

**Comment by ucLh** [comment]
Пока занимаю задачу до уточнения условий
